### PR TITLE
fix qmake.sh on darwin

### PR DESCRIPTION
**Pull request by hkiel**

### CODE REVIEW

**Comment by sjoelund** [comment]
Are you sure this one works?

**Comment by hkiel** [comment]
I tested it here on my machine, but had to tweak it into the build process (macports), so I'm quite sure it does what it should if inserting the patch worked fine.
At least I ran into the same error before and it now vanished...

**Comment by hkiel** [comment]
@sjoelund  I was a bit concerned about the single backslash in the brackets, but when putting the masked backslash (double backslash) it does not fix the bug anymore. This one works, I just created the .mpkg with it.

**Comment by sjoelund** [comment]
All the Qt submodules need to be updated to this OM-common hash in order for the builds to use it

**Comment by hkiel** [comment]
Can you do this?

**Pull request merged**
